/*
 * jpt2AXForm.java
 *
 * Created on November 10, 2006, 11:55 PM
 */

package tools;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author  miki
 */
@SuppressWarnings("serial")
public class jpt2DominoForm extends javax.swing.JFrame {
    
    /** Creates new form jpt2DominoForm */
    public jpt2DominoForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRUN = new javax.swing.JButton();
        jButtonBACK = new javax.swing.JButton();
        jButtonCHOOSEFile = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(204, 0, 0)), "jpt2Domino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 18));
        jLabel3.setText("jpt2domino - 2009");

        jLabel4.setText("Simple tool to convert tab files to Domino input");

        jLabel1.setText("jpt File");

        jButtonRUN.setText("run");
        jButtonRUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRUNActionPerformed(evt);
            }
        });

        jButtonBACK.setText("back");
        jButtonBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBACKActionPerformed(evt);
            }
        });

        jButtonCHOOSEFile.setText("choose file");
        jButtonCHOOSEFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCHOOSEFileActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(43, 43, 43)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(67, 67, 67)
                        .add(jLabel1)
                        .add(43, 43, 43)
                        .add(jButtonCHOOSEFile)
                        .add(69, 69, 69))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jButtonRUN)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 151, Short.MAX_VALUE)
                        .add(jButtonBACK)
                        .add(34, 34, 34))))
            .add(jPanel1Layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jLabel4)
                .addContainerGap(42, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(91, 91, 91)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 202, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .add(24, 24, 24)
                .add(jLabel4)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jButtonCHOOSEFile))
                .add(39, 39, 39)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonBACK)
                    .add(jButtonRUN))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton3.setText("exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .add(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unused")
	private void jButtonCHOOSEFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCHOOSEFileActionPerformed
        String currentDirectory;
        // currentDirectory = jPTForm().getCurrentDirectory();
        String curDir = System.getProperty("user.dir");
        //currentDirectory = "/Users/miki/Development/java/jPTGUI";
        JFileChooser fc = new JFileChooser(curDir);
        JFrame frame = null;
        fc.showOpenDialog(frame);
        File selFile = fc.getSelectedFile();
        System.out.println("selected file: "+selFile);
        setInputFile(selFile);
    }//GEN-LAST:event_jButtonCHOOSEFileActionPerformed

    private void jButtonBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBACKActionPerformed
        // RETURN BUTTON
        //hide the frame;
        setVisible(false);
    }//GEN-LAST:event_jButtonBACKActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // EXIT BUTTON
        System.exit(0);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonRUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRUNActionPerformed

        String inFile = getInputFile();
        try {
            //String outFile = jTextField2.getText();
            new jpt2Domino().jpt2Domino_calc(inFile);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonRUNActionPerformed
    
        private void setInputFile(File inputFile) {
        //throw new UnsupportedOperationException("Not yet implemented");
        this.inputFile = inputFile;
        return;
    }
    public String getInputFile(){
        String str = inputFile.toString();
        //return inputFile;
        return str;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jpt2DominoForm().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBACK;
    private javax.swing.JButton jButtonCHOOSEFile;
    private javax.swing.JButton jButtonRUN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private File inputFile;
    
}
